source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def standard_pods
    pod 'Hellfire', :path => '../'
end

target 'Hellfire_Example' do
  platform :ios, '10.0'
  standard_pods
end

  target 'Hellfire_Tests' do
    platform :ios, '10.0'
    standard_pods
end


